---
- hosts: all
  become: yes
  
  vars_files:
    - ../../vars/golang.yml
  
  roles:
  - ../../roles/andrewrothstein.go
  
  tasks:
    - name: create the go/src/github.com dir
      file:
        path: "{{go_user_path}}/src/github.com"
        state: directory
      when: go_user_path is defined

    - name: chown go dir to correct user
      file:
        path: "{{go_user_path}}"
        owner: "{{user_account_name}}"
        group: "{{user_account_name}}"
        mode: u=rwX,g=rX,o=rX
        recurse: yes
      when: user_account_name is defined and user_account_name != 'root'

    - name: create .bash_profile for user account and set go environment variables
      template:
        src: ../../templates/profile/bash_profile.j2
        dest: "{{user_account_path}}/.bash_profile"
        mode: 0644
      when: user_account_name is defined and user_account_name != 'root'
